services:
  db:
    image: postgres:18
    container_name: postgres-dev
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-dev
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/artifacts
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --allowed-hosts "*"
    depends_on:
      - db
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fraud-api
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_URI: models:/fraud-detection@production
      RELOAD_TOKEN: ${RELOAD_TOKEN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}
    depends_on:
      - mlflow
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000

volumes:
  postgres_data:
  mlflow_artifacts: